### ISSUE TITLE
Consultation on Code Issues

### ISSUE THREAD

**Issue by APPLE-XMT** [nguyentthong/gbdt_listwise_mrhp#1]
Hello, it is a great honor to read your paper. I would like to consult you about the code. During the model training, I found that a part of the code is missing. For example,"from allrank.models.losses import neuralNDCG, listNet". I did not find the module in the given code.

**Comment by thangld201** [comment]
You'd need to install [allrank](https://pypi.org/project/allRank/), I suppose.

`pip install allrank`
